// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void register() {
    driver.get("https://www.opencart.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".btn-black")).click();
    driver.findElement(By.id("input-username")).click();
    driver.findElement(By.id("input-firstname")).click();
    driver.findElement(By.id("input-firstname")).sendKeys("Alina");
    driver.findElement(By.id("input-lastname")).click();
    driver.findElement(By.id("input-lastname")).sendKeys("Artemenko");
    driver.findElement(By.id("input-email")).click();
    driver.findElement(By.id("input-email")).sendKeys("artemenko.alina26@gmail.com");
    driver.findElement(By.id("input-password")).click();
    driver.findElement(By.id("input-password")).sendKeys("test26052024");
    driver.findElement(By.cssSelector("form .col-sm-6:nth-child(1)")).click();
    driver.findElement(By.cssSelector("form .col-sm-6:nth-child(2)")).click();
    driver.findElement(By.id("input-email")).click();
    driver.findElement(By.cssSelector(".col-md-7")).click();
    driver.findElement(By.id("input-password")).click();
    driver.findElement(By.id("account-register")).click();
    driver.findElement(By.id("input-username")).click();
    driver.findElement(By.id("input-username")).sendKeys("alinaart");
    driver.findElement(By.id("input-password")).sendKeys("test26052024");
    driver.findElement(By.cssSelector(".btn-lg:nth-child(1)")).click();
    driver.findElement(By.xpath("//input")).click();
    driver.findElement(By.xpath("//input")).sendKeys("2607");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    driver.findElement(By.cssSelector("li:nth-child(4) img")).click();
    driver.findElement(By.cssSelector(".btn-lg:nth-child(1)")).click();
  }
}
